// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./../components/ui/BaseButton.vue')['default']
    FeatherLoader: typeof import('~icons/feather/loader')['default']
    HeroiconsSolidChevronDown: typeof import('~icons/heroicons-solid/chevron-down')['default']
    HeroiconsSolidChevronUp: typeof import('~icons/heroicons-solid/chevron-up')['default']
    HeroiconsSolidExclamationCircle: typeof import('~icons/heroicons-solid/exclamation-circle')['default']
    TablerLoader: typeof import('~icons/tabler/loader')['default']
    TheInputField: typeof import('./../components/forms/TheInputField.vue')['default']
  }
}

export { }
